### ISSUE TITLE
New Feature Requested : Export loan history under CSV/.xls or other

### ISSUE THREAD

**Issue by lilinx** [ideas-box/ideasbox.lan#156]
Hello,
I'm in Mapoon right now with the box ! Thank to all the contributors.

I urgently need this feature. For reporting, the Box Coordinator will regularly export to CSV and send by email : 1) the user database (no problem) 2) the "entries" database (attendance to the ideas box, also not a problem 3) the loan history (there is no feature to export this data to csv)

This urgent and important ; i'm leaving Mapoon on Friday ; and this is the main analytic requested by the partners so we need a way to have access to these stats.

Thank you !
Pierre

**Comment by yohanboniface** [comment]
I'll have a look at this tonight.

**Comment by yohanboniface** [comment]
@lilinx if you are up already, here are the fields I'm going to put on the CSV:
- item name
- item barcode
- user serial
- creation date
- due date
- status (returned or not)
- comments (optional)

Anything to add?
