### ISSUE TITLE
Easy way to add link application

### ISSUE THREAD

**Issue by fheslouin** [ideas-box/ideasbox.lan#164]
Would it be possible to have an easy way to add multiple application link on main page ? 
Currently we have to modify base.conf, django templating and CCS files...
Do you think it could be done in one file conf ?

**Comment by yohanboniface** [comment]
Yeah, that's doable. A dict in the config, with name, description, category and image would do the job, what do you think?

Something like:

```python
EXTERNAL_APPS = [{
    "name": "Wikipedia",
    "description": "Wikipedia blahblah",
    "category": "learn",
    "img": "path/to/img"
}]
```
Or, given that I think in the beginning we still only have a closed list of possible app, we can create all in the core and only activate them or not through config:

```python
EXTERNAL_APPs = ['wikipedia', 'kalite']
```

Thoughts?

**Comment by fheslouin** [comment]
Whoua ! Great, I would rather use the first dict. 
We are going to have between 3 to 7 apps on the main page and this is great if we can set image, category and so on.

**Comment by fheslouin** [comment]
As we discuss is it possible to have some "defaults" app to enable/disable and a dict in a config file to add custom apps ?

**Comment by yohanboniface** [comment]
Yes. If not done during this sprint, that's my number one task when I'm in BSF Wednesday.

And if someone want to work on it here are quick specs:

Goal: allow to customize the links of the home page (cards); now there are only Wikipedia and KA-Lite
How:
- add a setting (HOME_CARDS or whatever) which is a list of either a string id or a dict
- on the home page, loop over this list, when you have a string, consider there is a template with the id existing in `ideasbox/cards/{id}.html`, if not raise; if it's a dict, build a card from a generic card template; dict must contain: name, description, category (learn, read…) and an image path.
- by default, the `HOME_CARDS` settings is ['wikipedia', 'kalite']
