### ISSUE TITLE
management command for batch processing documents

### ISSUE THREAD

**Issue by yohanboniface** [ideas-box/ideasbox.lan#29]
- Should guess the title from the document name
- no description by default
- add a --tags arg to define tags for all processed documents

**Comment by yohanboniface** [comment]
Discussed with Grégoire, medata are in a CSV file, for example:

kind | path | title | summary | lang | credits | tags | preview
----- | ------ | ---- | ------------ | -----  | -------- | ------ | ---------
jpg | 6857462096_55c4b458a8_o.jpg | Nature | Une route enneigée | fr | John Bon, Creative Commons | photo, nature | 
jpg | 13304885523_47683a6f4f_o.jpg | Fleur et bourdon | Le printemps revient | fr | Mila Dart, Creative Commons | photo, nature, fleurs | 
jpg | 16823997277_d5d5b0a124_o.jpg | Campagne | Massif duu Sancy, octobre 2004 | fr | Patrick Swaize, Creative Commons | photo, nature | 
mp4 | Enfulte - Studio Bagel.mp4 | En fulte | Baptiste et Max Boublil jouent au gendarme et au voleur.  | fr | Studio Bagel, Creative commons | Humour, policier | 
mp4 | Meet the Ideas Box A LibraryMedia Center ready in 20 minutes.mp4 | Meet the Ideas Box: A Library/Media Center ready in 20 minutes! | The Ideas Box is a portable multimedia center for vulnerable people in humanitarian situations created by the NGO Libraries Without Borders / Bibliothèques Sans Frontières. Designed by Philip Starck and developed in partnership of UNHCR.  | en | BSF, Creative Commons | Ideas Box, ONG, BSF | 16823997277_d5d5b0a124_o.jpg
pdf | xProust-01.pdf | Du côté de chez Swann. Première partie. | Cette édition numérisée reprend le texte de l’édition Gallimard, Paris, 1946-47, en 15 volumes. | fr | Marcel Proust, Domaine public | littérature, roman | 
pdf | xProust-02.pdf | Du côté de chez Swann. Deuxième partie. | Cette édition numérisée reprend le texte de l’édition Gallimard, Paris, 1946-47, en 15 volumes. | fr | Marcel Proust, Domaine public | littérature, roman | 
pdf | Proust-03.pdf | À l’ombre des jeunes filles en fleurs. Première partie. | Cette édition numérisée reprend le texte de l’édition Gallimard, Paris, 1946-47, en 15 volumes. | fr | Marcel Proust, Domaine public | littérature, roman | 

Then all medias must be relative to this CSV.

Example of command line call:

    python ideasbox import_medias path/to/metadata.csv

**Comment by Peh4** [comment]
Hello,

The "lang" column is strange for me, it will be impossible to translate
Titles Summaries and tags ?

Bests

--
PA



2015-10-10 11:24 GMT+02:00 Yohan Boniface <notifications@github.com>:

**Comment by yohanboniface** [comment]
> it will be impossible to translate Titles Summaries and tags ?

Not in this application version.

**Comment by fheslouin** [comment]
Great ! working, except something with unicode in some files
```
✔
[KB_Liste_contenus_videos+fiches.xlsx](https://github.com/ideas-box/ideasbox.lan/files/12638/KB_Liste_contenus_videos.fiches.xlsx)

 Uploaded media BANA BOUL – CONJUGAISON – OOSTA
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.virtualenvs/ideasbox/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/root/.virtualenvs/ideasbox/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.virtualenvs/ideasbox/local/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.virtualenvs/ideasbox/local/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/ideasbox.lan/ideasbox/mediacenter/management/commands/import_medias.py", line 58, in handle
    self.add(row)
  File "/home/ideasbox.lan/ideasbox/mediacenter/management/commands/import_medias.py", line 84, in add
    return self.skip('Path not found: {}'.format(path), metadata)
  File "/home/ideasbox.lan/ideasbox/mediacenter/management/commands/import_medias.py", line 32, in skip
    self.stderr.write(u'⚠ Skipping. {}.'.format(msg))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 63: ordinal not in range(128)
```

Here is the path value : 
```
BANA BOUL - CONJUGAISON - ROOSTA.mp4
```
Find in attachment the xlsx file before conversion in CSV.

**Comment by fheslouin** [comment]
Most of videos cannot be viewed : 
```Aucune vidéo dont le format ou le type MIME est gérée n'a été trouvée.```

**Comment by yohanboniface** [comment]
Humm, I don't see the CSV.
Also, what video formats?

**Comment by fheslouin** [comment]
[KB_Liste_contenus_videos+fiches.txt](https://github.com/ideas-box/ideasbox.lan/files/12699/KB_Liste_contenus_videos.fiches.txt)
This is a CSV rename in TXT file (GitHub policy)

Videos are in MP4, it should actually work. I try tomorrow to upload one or two manually to see if I got the same error.

**Comment by fheslouin** [comment]
Everything is working, thanks
