### ISSUE TITLE
debian package

### ISSUE THREAD

**Issue by yohanboniface** [ideas-box/ideasbox.lan#32]
We want to be able to install the project from with `apt-get install` in our server, so we'll need a package.

Things to take care of:
- [x] templates
- [x] static files
- [ ] user uploaded content
- [x] nginx vhost activation (or other server strategy)
- [x] i18n
- [x] migrations
- [x] service like daemon to run django (with gunicorn?)
- [x] create a first user at first run
- [x] autostart daemon at server boot

**Comment by yohanboniface** [comment]
A bit of doc:
- https://wiki.debian.org/DjangoPackagingDraft
- http://www.laurentluce.com/posts/hello-world/

**Comment by yohanboniface** [comment]
Examples:
- http://bazaar.launchpad.net/~zkrynicki/+junk/django_hello/files
- http://bazaar.launchpad.net/~zkrynicki/ubuntu/lucid/django-testproject/packaging/files

**Comment by yohanboniface** [comment]
- http://stackoverflow.com/questions/4452208/package-a-django-project-and-its-dependencies-for-a-standalone-product
- http://www.radix50.net/~ibr/notes/20080323-0-django-autotools-debian.html

**Comment by yohanboniface** [comment]
https://hynek.me/articles/python-app-deployment-with-native-packages/

**Comment by yohanboniface** [comment]
Parcel is a suite of classes and helper functions designed to be used in conjunction with Fabric for building and deploying Python web applications using native packages.

http://parcel.readthedocs.org/en/latest/user/quickstart.html

**Comment by yohanboniface** [comment]
https://hynek.me/articles/virtualenv-lives/

**Comment by xordoquy** [comment]
https://github.com/spotify/dh-virtualenv

**Comment by yohanboniface** [comment]
Example of Nginx postinst scripts:
- https://github.com/quarkslab/irma-frontend/blob/master/debian/irma-frontend-nginx.postinst
- https://github.com/codebutler/ubuntu-packages/blob/master/nginx/debian/postinst

**Comment by yohanboniface** [comment]
Example using dh_virtualenv: https://github.com/goodguy/debian-virtualenv-skeleton

**Comment by yohanboniface** [comment]
May be interesting to publish packages, as we can't publish dh_virtualenv made packages from launchpad: https://packagecloud.io/

**Comment by yohanboniface** [comment]
For the record: https://nylas.com/blog/packaging-deploying-python

**Comment by yohanboniface** [comment]
https://github.com/nylas/make-deb
